In [1]:
import numpy as np


In [2]:
# Create an array from a list 

a = np. array([1,2,3])

print('array a :', a )

array a : [1 2 3]


In [3]:
# Create an array with evenly spaced values 
b = np.arange(0,10,3) 
print('array b :', b)

array b : [0 3 6 9]


In [4]:
# Create an array filled with zeros 
d = np.zeros((2,3))
print('array d: \n',d )

array d: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
d_int = np.zeros((2,3), dtype=int)
print(d_int)

[[0 0 0]
 [0 0 0]]


In [6]:
e = np.ones((3,2))
e_int = np.ones((3,2), dtype=int)
print('e =', e)
print('e_int =', e_int)

e = [[1. 1.]
 [1. 1.]
 [1. 1.]]
e_int = [[1 1]
 [1 1]
 [1 1]]


In [7]:
f = np.eye(4)
f_int= np.eye((4),dtype=int)

print(f)
print(f_int)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [8]:
# Reshape 

a1 = np.array([1,2,3])
reshaped_row = np.reshape(a1,(1,3)) 
reshaped_col = np.reshape(a1,(3,1))

print('a1 =',a1)
print('reshaped_row =',reshaped_row)
print('reshaped_col =',reshaped_col)

a1 = [1 2 3]
reshaped_row = [[1 2 3]]
reshaped_col = [[1]
 [2]
 [3]]


In [9]:
# Flatten (matrix --> 1D Vector)

f1 = np.array([ [1,2],[3,4],[5,6], [7,8],[9,10] ])
flattened = np.ravel(f1) 

print(f1)

print(flattened)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
# Transpose (row <---> columns)

e1 = np.array([ [1,2], [3,4]])
transposed = np.transpose(e1)

print('e1 =',e1)
print('transposed =',transposed)

e1 = [[1 2]
 [3 4]]
transposed = [[1 3]
 [2 4]]


In [11]:
# Vertical stacking 
a2, b2 = np.array([1,2]), np.array([3,4])
v_stack = np.vstack([a2,b2]) 

print('a2 & b2 =', a2, b2)

print('v_stack =',v_stack)

a2 & b2 = [1 2] [3 4]
v_stack = [[1 2]
 [3 4]]


In [12]:
# Horizontal stacking 

h_stack = np.hstack([a2,b2])
print(h_stack)

[1 2 3 4]


# Mathematical Functions 



In [13]:
g = np.array([1,2,3,4])

np.add(g,2)

array([3, 4, 5, 6])

In [14]:
np.power(g,2)

array([ 1,  4,  9, 16], dtype=int32)

In [15]:
np.sqrt(g)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [16]:
# dot product - multiply elements and sum them 
a = np.array([1,2,3])
np.dot(a,g[:3])   # (1x1)+(2x2)+(3x3) = 14

14

# Stastistical Functions 



In [17]:
s = np.array([1,2,3,4])

np.mean(s)

2.5

In [18]:
np.var(s) # variance (how spread out numbers are)

1.25

In [19]:
np.std(s) # — standard deviation (root of variance)

1.118033988749895

In [20]:
print(np.min(s))
print(np.max(s))


1
4


# `````Random sampling Function 

In [21]:
# Random floats between 0 and 1 

np.random.rand(3)   # output change in every run 

array([0.05740796, 0.86480834, 0.29128272])

In [22]:
np.random.seed(0) # Set seed — makes random numbers reproducible
print(np.random.rand(3))


[0.5488135  0.71518937 0.60276338]


In [23]:
np.random.randint(0,10, size=5)

array([3, 7, 9, 3, 5])

In [24]:
np.random.seed(0)
np.random.randint(0,10, size=5)

array([5, 0, 3, 3, 7])

# `````Boolean & logical functions



In [25]:
logical_test = np.array([True, False, True])

np.all(logical_test)     # False — ALL must be True

False

In [26]:
np.any(logical_test)  # True  — at least ONE is True

True

In [27]:
np.all(np.array([True, True]))


True

In [28]:
np.all(np.array([False,False]))

False

# ```````Set Operations

In [29]:
set_a = np.array([1,2,3,4])
set_b = np.array([3,4,5,6])

np.intersect1d(set_a,set_b)  # [3, 4]  — common elements

array([3, 4])

In [30]:
np.union1d(set_a, set_b)

array([1, 2, 3, 4, 5, 6])

# ``` Array attributes 


In [31]:
a = np.array([1,2,3])


In [32]:
print('a.shape = ',a.shape)
print('a.size =', a.size)
print('a.ndim =',a.ndim)  # number of dimensions
print('a.dtype =',a.dtype)  # data type of elements
print('a.nbytes =',a.nbytes)   # memory size in bytes

a.shape =  (3,)
a.size = 3
a.ndim = 1
a.dtype = int32
a.nbytes = 12


# ````Other Utility Functions 



In [33]:
a = np.array([1,2,3])
copied_array = np.copy(a)


print(a)
print(copied_array)

print(np.shares_memory(a,copied_array))  # # False — separate memory
 
    
    
b = a[:]

print(np.shares_memory(a,b)) # # True — same memory block!
 
      

[1 2 3]
[1 2 3]
False
True


# Python Basics Functions & list 

In [35]:
def wish():
    print('Hare Krishna!')
    

In [38]:
wish()
wish()


Hare Krishna!
Hare Krishna!


# Otp Generator Program 

In [68]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of specified length."""
    digits = '0123456789'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp


In [69]:
otp_length = 4
otp = generate_otp(otp_length)
print(f'your OTP is: {otp}')

your OTP is: 8405


# List methods - .pop() , .copy() , .append()

In [74]:
x = [1,2,3]
x.append(4)
print(x)

[1, 2, 3, 4]


In [75]:
y = x.copy()
x.append(5)

print(y)
print(x)

[1, 2, 3, 4]
[1, 2, 3, 4, 5]


In [79]:
list1 = ['a','b','g',1,5]


In [80]:
print(list1)
print(list1.pop) # # prints function reference, NOT result
print(list1.pop())  ## prints 5 and removes it from list

['a', 'b', 'g', 1, 5]
<built-in method pop of list object at 0x00000230D32D9140>
5
